document.writeln("  <div id=\'help\' class=\'minW\'>");
document.writeln("        <div class=\'help_content pad\'>");
document.writeln("          <ul class=\'help_list\'>");
document.writeln("            <li>");
document.writeln("              <a href=\'#\' class=\'ib\'>");
document.writeln("                <p class=\'iconfont icon-qitianwuliyoutuihuanhuo\'></p>");
document.writeln("                <p>七天七天换货</p>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'#\' class=\'ib\'>");
document.writeln("                <p class=\'iconfont icon-7tiantuihuo\'></p>");
document.writeln("                <p>七天七天换货</p>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'#\' class=\'ib\'>");
document.writeln("                <p class=\'iconfont icon-huanhuo\'></p>");
document.writeln("                <p>七天七天换货</p>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'#\' class=\'ib\'>");
document.writeln("                <p class=\'iconfont icon-liwu\'></p>");
document.writeln("                <p>七天七天换货</p>");
document.writeln("              </a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("");
document.writeln("      <div class=\'minW\' id=\'aboutUs\'>");
document.writeln("        <div id=\'au_content\' class=\'pad\'>");
document.writeln("          <ul class=\'au_list\'>");
document.writeln("            <li class=\'fl\'>");
document.writeln("              <ul class=\'au_list_list\'>");
document.writeln("                <li class=\'top\'>");
document.writeln("                  一加产品");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'fl\'>");
document.writeln("              <ul class=\'au_list_list\'>");
document.writeln("                <li class=\'top\'>");
document.writeln("                  一加产品");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'fl\'>");
document.writeln("              <ul class=\'au_list_list\'>");
document.writeln("                <li class=\'top\'>");
document.writeln("                  一加产品");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </li>");
document.writeln("            <li class=\'fl\'>");
document.writeln("              <ul class=\'au_list_list\'>");
document.writeln("                <li class=\'top\'>");
document.writeln("                  一加产品");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#\'>OnePlus6</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("          <div class=\'connectUs tc\'>");
document.writeln("            <a href=\'#\' class=\'phone ib\'><span class=\'iconfont icon-call\'></span>400-888-1111</a>");
document.writeln("            <a href=\'\' class=\'ib sever pr on_btn\'>联系客服</a>");
document.writeln("            <p class=\'time\'>周一至周日 9:00 - 22:00</p>");
document.writeln("            <a href=\'#\' class=\'weixin\'><span class=\'iconfont icon-weixin\'></span></a>");
document.writeln("            <a href=\'#\' class=\'weibo\'><span class=\'iconfont icon-weibo-copy\'></span></a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("");
document.writeln("      <div id=\'copy\' class=\'miniW\'>");
document.writeln("        <div class=\'copy_content pad\'>");
document.writeln("          <a href=\'#\' class=\'ib language fl\'><span style=\'top:2px\' class=\'pr iconfont icon-zhongguo\'></span>中文（简体中文）</a>");
document.writeln("          <p class=\'fr\'>");
document.writeln("            <a href=\'#\'>隐私政策</a>");
document.writeln("            <span class=\'ib\'></span>");
document.writeln("            <a href=\'#\'>用户协议</a>");
document.writeln("          </p>");
document.writeln("        </div>");
document.writeln("        <div class=\'copy_copy pad clearfix\'>");
document.writeln("          <div class=\'fl copy_left\'  style=\'line-height:33px\'>");
document.writeln("            <p>&copy;2013-2018 OnePlus. All Rights Reserved. (粤ICP备13080605号-4)</p>");
document.writeln("            <p><a href=\'#\'><img src=\'img/badge.png\' alt=\'\'>粤公网安备 44030402001407号</a></p>");
document.writeln("          </div>");
document.writeln("          <a href=\'#\'><img width=\'83px\' class=\'fr\' src=\'img/cnnic.png\' alt=\'\'></a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
