document.writeln("  <div class=\'nav\'>");
document.writeln("        <div id=\'nav_content\' class=\'pad\'>");
document.writeln("          <div id=\'logo\' class=\'fl\'>");
document.writeln("            <a href=\'index.html\' class=\'iconfont icon-yijia\'></a>");
document.writeln("          </div>");
document.writeln("          <div style=\'display:none\' class=\'search_Box fl\'>");
document.writeln("            <form class=\'searchBox\' action=\'index.html\' method=\'post\'>");
document.writeln("              <span class=\'iconfont icon-fangdajing\'></span><input type=\'text\' name=\'\' placeholder=\'搜索商品\' value=\'\'>");
document.writeln("              <span class=\'iconfont icon-x searchclose\'></span>");
document.writeln("              <ul style=\'display:none\'  class=\'search_list pa\' >");
document.writeln("                <li><a href=\'#\'>一加一加1加</a></li>");
document.writeln("                <li><a href=\'#\'>一加一加2加</a></li>");
document.writeln("                <li><a href=\'#\'>一加一加3加</a></li>");
document.writeln("                <li><a href=\'#\'>一加一加4加</a></li>");
document.writeln("                <li><a href=\'#\'>一加一加5加</a></li>");
document.writeln("              </ul>");
document.writeln("            </form>");
document.writeln("          </div>");
document.writeln("          <ul id=\'nav_list\' class=\'fl\'>");
document.writeln("            <li class=\'fl\'><a class=\'ib\' href=\'product.html\'>Oneplus6</a></li>");
document.writeln("            <li class=\'fl\'><a class=\'ib\' href=\'detail.html\'>商城</a></li>");
document.writeln("            <li class=\'fl\'><a class=\'ib\' href=\'detail.html\'>论坛</a></li>");
document.writeln("            <li class=\'fl\'><a class=\'ib\' href=\'detail.html\'>服务</a></li>");
document.writeln("            <li class=\'fl\'><a class=\'ib\' href=\'detail.html\'>博客</a></li>");
document.writeln("          </ul>");
document.writeln("          <div id=\'login_box\' class=\'fr \'>");
document.writeln("            <ul class=\'pr\'>");
document.writeln("              <li class=\'fl\' id=\'login_btn\'>");
document.writeln("                <a href=\'#\' class=\'iconfont icon-yonghutouxiang ib login_change\'></a>");
document.writeln("                <div class=\'loginSele pa\'>");
document.writeln("                  <ul class=\'\'>");
document.writeln("                    <li><a href=\'#\'>订单</a></li>");
document.writeln("                    <li><a href=\'#\'>账户</a></li>");
document.writeln("                    <li><a href=\'#\'>推荐有礼</a></li>");
document.writeln("                    <li class=\'loginbtn\'><a style=\'color: #09c;\' href=\'#\'>登录</a></li>");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("              </li>");
document.writeln("              <li id=\'buycar\' class=\'fl\'>");
document.writeln("                <a href=\'#\' class=\'iconfont icon-gouwudai_o ib login_change\'></a>");
document.writeln("                <div class=\'buycar tc pa\'>");
document.writeln("                  <ul class=\'smallBuyCar\'>");
document.writeln("                  <li style=\'padding:10px 0;\' class=\'bc-nopro  tc\'>您的购物车里没有商品</li>");
document.writeln("                  </ul>");
document.writeln("                  <a href=\'./detail.html\' class=\'ib pr buycarbtn on_btn \'>");
document.writeln("                    去购物");
document.writeln("                  </a>");
document.writeln("                </div>");
document.writeln("              </li>");
document.writeln("              <li class=\'fl\'>");
document.writeln("                <a id=\'research\' href=\'#\' class=\'iconfont icon-fangdajing ib login_change\'></a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
